Merge branch 'master' into bsp_mcx

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -1,4 +1,4 @@
-name: RT-Thread
+name: RT-Thread BSP build check
 
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
@@ -33,39 +33,45 @@ jobs:
       fail-fast: false
       matrix:
        legs:
-         -  RTT_BSP: "others" 
+         -  RTT_BSP: "others_at32_hc32"
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP: 
+                - "qemu-vexpress-a9"
                 - "airm2m/air32f103"
+                #- "airm2m/air105"
                 - "acm32/acm32f0x0-nucleo"
                 - "CME_M7"
                 - "apollo2"
                 - "asm9260t"
                 - "allwinner_tina"
                 - "ft32/ft32f072xb-starter"
-                - "lm3s8962"
-                - "lm3s9b9x"
-                - "lm4f232"
-                - "tm4c123bsp"
-                - "tkm32F499"
-                - "tm4c129x"
                 - "mini2440"
-                - "mm32/mm32f3270-100ask-pitaya"
-                - "qemu-vexpress-a9"
-                - "sam7x"   
                 - "at91/at91sam9g45"
                 - "at91/at91sam9260"
-                - "renesas/ra6m3-ek"
-                - "renesas/ra6m4-cpk"
                 - "wch/arm/ch32f103c8-core"
                 - "wch/arm/ch32f203r-evt"
                 - "synwit/swm320"
                 - "synwit/swm341"
                 - "beaglebone"
                 - "zynqmp-r5-axu4ev"
-                - "frdm-k64f"
-                - "xplorer4330/M4"
-         -  RTT_BSP: "stm32l4" 
+                - "at32/at32f403a-start"
+                - "at32/at32f407-start"
+                - "at32/at32f413-start"
+                - "at32/at32f415-start"
+                - "at32/at32f421-start"
+                - "at32/at32f423-start"
+                - "at32/at32f425-start"
+                - "at32/at32f435-start"
+                - "at32/at32f437-start"
+                - "yichip/yc3122-pos"
+                - "hc32/ev_hc32f4a0_lqfp176"
+                - "hc32/ev_hc32f460_lqfp100_v2"
+                - "hc32l196"
+                #- "tae32f5300"
+                - "mm32/mm32f3270-100ask-pitaya"
+                - "sam7x"   
+                - "hk32/hk32f030c8-mini"
+         -  RTT_BSP: "stm32l4_f0_f1" 
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP: 
                 - "stm32/stm32l4r5-st-nucleo"
@@ -84,6 +90,7 @@ jobs:
                 - "stm32/stm32l476-st-nucleo"
                 - "stm32/stm32l496-ali-developer"
                 - "stm32/stm32l496-st-nucleo"
+                - "stm32/stm32l496-st-discovery"
                 - "stm32/stm32f072-st-nucleo"
                 - "stm32/stm32f091-st-nucleo"
                 - "stm32/stm32f103-100ask-mini"
@@ -100,11 +107,12 @@ jobs:
                 - "stm32/stm32f103-yf-ufun"
                 - "stm32/stm32f103-ys-f1pro"
                 - "stm32/stm32f107-uc-eval"
-         -  RTT_BSP: "stm32-1" 
+         -  RTT_BSP: "stm32_f2_f4" 
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP: 
                 - "stm32/stm32f207-st-nucleo"
                 - "stm32/stm32f302-st-nucleo"
+                - "stm32/stm32f334-st-nucleo"
                 - "stm32/stm32f401-st-nucleo"
                 - "stm32/stm32f401-weact-blackpill"
                 - "stm32/stm32f405-smdz-breadfruit"
@@ -125,7 +133,7 @@ jobs:
                 - "stm32/stm32f429-st-disco"
                 - "stm32/stm32f446-st-nucleo"
                 - "stm32/stm32f469-st-disco"
-         -  RTT_BSP: "stm32-2" 
+         -  RTT_BSP: "stm32_f7_g0_h7_mp15_u5_wb5" 
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP: 
                 - "stm32/stm32f746-st-disco"
@@ -151,11 +159,9 @@ jobs:
                 - "stm32/stm32mp157a-st-ev1"
                 - "stm32/stm32u575-st-nucleo"
                 - "stm32/stm32wb55-st-nucleo"
-         -  RTT_BSP: "nxp" 
+         -  RTT_BSP: "nxp_renesas" 
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP: 
-                - "lpc43xx/M4"
-                - "lpc176x"
                 - "lpc55sxx/lpc55s69_nxp_evk"
                 - "lpc55sxx/lpc55s28_nxp_evk"
                 - "lpc55sxx/lpc55s06_nxp_evk"
@@ -175,7 +181,14 @@ jobs:
                 - "imxrt/imxrt1052-seeed-ArchMix"
                 - "imxrt/imxrt1060-nxp-evk"
                 - "imxrt/imxrt1064-nxp-evk"
-         -  RTT_BSP: "gd32_n32" 
+                - "frdm-k64f"
+                - "lpc176x"
+                - "xplorer4330/M4"
+                #- "lpc43xx/M4"
+                - "renesas/ra6m3-ek"
+                - "renesas/ra6m4-cpk"
+                - "renesas/ra6m3-hmi-board"  
+         -  RTT_BSP: "gd32_n32_apm32"   
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP:             
                 - "gd32/arm/gd32103c-eval" 
@@ -206,7 +219,19 @@ jobs:
                 - "n32/n32l43xrl-stb"
                 - "n32/n32l436-evb"
                 - "n32/n32wb45xl-evb"
-         -  RTT_BSP: "nordic_Infineon_apm32" 
+                - "apm32/apm32f103xe-minibroard"
+                - "apm32/apm32f407ig-minibroard"
+                - "apm32/apm32f407zg-evalboard"
+                - "apm32/apm32f072vb-miniboard"
+                - "apm32/apm32f107vc-evalboard"
+                - "apm32/apm32f030r8-miniboard"
+                - "apm32/apm32f051r8-evalboard"
+                - "apm32/apm32f091vc-miniboard"
+                - "apm32/apm32f103vb-miniboard"
+                - "apm32/apm32e103ze-evalboard"
+                - "apm32/apm32e103ze-tinyboard"
+                - "apm32/apm32s103vb-miniboard"
+         -  RTT_BSP: "nordic_Infineon_TI_microchip" 
             RTT_TOOL_CHAIN: "sourcery-arm"
             SUB_RTT_BSP:  
                 - "nrf5x/nrf51822"
@@ -220,43 +245,30 @@ jobs:
                 - "Infineon/psoc6-cy8ckit-062-WIFI-BT"
                 - "Infineon/psoc6-cy8cproto-062S3-4343W"
                 - "Infineon/psoc6-evaluationkit-062S2"
-                - "apm32/apm32f103xe-minibroard"
-                - "apm32/apm32f407ig-minibroard"
-                - "apm32/apm32f072vb-miniboard"
-                - "apm32/apm32f107vc-evalboard"
-                - "apm32/apm32f030r8-miniboard"
-                - "apm32/apm32f051r8-evalboard"
-                - "apm32/apm32f091vc-miniboard"
-                - "apm32/apm32f103vb-miniboard"
-                - "at32/at32f403a-start"
-                - "at32/at32f407-start"
-                - "at32/at32f413-start"
-                - "at32/at32f415-start"
-                - "at32/at32f421-start"
-                - "at32/at32f425-start"
-                - "at32/at32f435-start"
-                - "at32/at32f437-start"
-                - "smartfusion2"
-                - "hc32/ev_hc32f4a0_lqfp176"
-                - "hc32/ev_hc32f460_lqfp100_v2"
-                - "hc32l196"
-                - "tae32f5300"
-                - "raspberry-pico"
-                - "raspberry-pi/raspi3-32"
-                - "raspberry-pi/raspi4-32"
-                - "microchip/samc21"
-                - "microchip/same54"
-                - "microchip/same70"
                 - "fujitsu/mb9x/mb9bf500r"
                 - "fujitsu/mb9x/mb9bf506r"
                 - "fujitsu/mb9x/mb9bf618s"
                 - "fujitsu/mb9x/mb9bf568r"
+                - "raspberry-pico"
+                - "raspberry-pi/raspi3-32"
+                - "raspberry-pi/raspi4-32"
+                - "lm3s8962"
+                - "lm3s9b9x"
+                - "lm4f232"
+                - "tm4c123bsp"
+                - "tm4c129x"
+                - "microchip/samc21"
+                - "microchip/same54"
+                - "microchip/same70"
+                - "smartfusion2"
+                - "maxim/max32660-evsys"
+                - "efm32"
          -  RTT_BSP: "mips" 
             RTT_TOOL_CHAIN: "sourcery-mips"
             SUB_RTT_BSP:  
                 - "loongson/ls1bdev"
-                - "loongson/ls1cdev"
                 - "loongson/ls2kdev"
+                - "loongson/ls1cdev"
          -  RTT_BSP: "aarch64" 
             RTT_TOOL_CHAIN: "sourcery-aarch64"
             SUB_RTT_BSP:  
@@ -264,7 +276,6 @@ jobs:
                 - "raspberry-pi/raspi3-64"
                 - "raspberry-pi/raspi4-64"
                 - "rockchip/rk3568"
-
          -  RTT_BSP: "riscv-none" 
             RTT_TOOL_CHAIN: "sourcery-riscv-none-embed"
             SUB_RTT_BSP:  
@@ -276,6 +287,16 @@ jobs:
                 - "bluetrum/ab32vg1-ab-prougen"
                 - "bouffalo_lab/bl60x"
                 - "bouffalo_lab/bl70x"
+         -  RTT_BSP: "llvm-arm" 
+            RTT_TOOL_CHAIN: "llvm-arm"
+            SUB_RTT_BSP:  
+                - "stm32/stm32l475-atk-pandora"
+                - "renesas/ra6m3-hmi-board"
+         -  RTT_BSP: "simulator" 
+            RTT_TOOL_CHAIN: "gcc"
+            SUB_RTT_BSP:  
+                - "simulator"
+
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python
@@ -287,7 +308,7 @@ jobs:
         shell: bash
         run: |
           sudo apt-get update
-          sudo apt-get -qq install gcc-multilib libncurses5-dev scons
+          sudo apt-get -qq install gcc-multilib libncurses5 libncurses5-dev libncursesw5-dev scons
           sudo python -m pip install --upgrade pip -qq
           pip install requests -qq
           git config --global http.postBuffer 524288000
@@ -303,6 +324,16 @@ jobs:
           sudo tar xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -C /opt
           /opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc --version
           echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_ENV
+
+      - name: Install LLVM-Arm ToolChains
+        if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'llvm-arm' && success() }}
+        shell: bash
+        run: |
+          wget -q https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-16.0.0/LLVMEmbeddedToolchainForArm-16.0.0-Linux-x86_64.tar.gz
+          sudo tar zxf LLVMEmbeddedToolchainForArm-16.0.0-Linux-x86_64.tar.gz -C /opt
+          /opt/LLVMEmbeddedToolchainForArm-16.0.0-Linux-x86_64/bin/clang --version
+          echo "RTT_CC=llvm-arm" >> $GITHUB_ENV
+          echo "RTT_EXEC_PATH=/opt/LLVMEmbeddedToolchainForArm-16.0.0-Linux-x86_64/bin" >> $GITHUB_ENV
 
       - name: Install AArch64 ToolChains
         if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-aarch64' && success() }}
@@ -326,7 +357,7 @@ jobs:
         if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-riscv64-unknown-elf' && success() }}
         run: |
           wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
-          sudo tar zxvf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
+          sudo tar zxf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz -C /opt
           /opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/riscv64-unknown-elf-gcc --version
           echo "RTT_EXEC_PATH=/opt/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin" >> $GITHUB_ENV
 
@@ -334,9 +365,14 @@ jobs:
         if: ${{ matrix.legs.RTT_TOOL_CHAIN == 'sourcery-riscv-none-embed' && success() }}
         run: |
           wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/v1.5/xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz
-          sudo tar zxvf xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz -C /opt
+          sudo tar zxf xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz -C /opt
           /opt/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin/riscv-none-embed-gcc --version
           echo "RTT_EXEC_PATH=/opt/xpack-riscv-none-embed-gcc-8.3.0-2.3/bin" >> $GITHUB_ENV
+
+      - name: Install Simulator Tools
+        if: ${{ matrix.legs.RTT_BSP == 'simulator' && success() }}
+        run: |
+          sudo apt-get -qq install libsdl2-dev
 
       - name: Bsp Scons Compile
         if: ${{ success() }}
@@ -347,8 +383,19 @@ jobs:
           SRTT_BSP: ${{ join(matrix.legs.SUB_RTT_BSP, ',') }}
         run: |
           source ~/.env/env.sh
+          failed=0
+          count=0
           for bsp in $(echo $SRTT_BSP | tr ',' '\n'); do
-            echo "Compiling BSP: ===== $bsp ===="
+            count=$((count+1))
+            echo "::group::Compiling BSP: ==$count=== $bsp ===="
+            echo bsp/$bsp
+            ls bsp/$bsp/Kconfig && scons -C bsp/$bsp --pyconfig-silent
             pushd bsp/$bsp && pkgs --update && popd
-            scons -C bsp/$bsp -j8
+            scons -C bsp/$bsp -j$(nproc) --debug=time | tee output.log || \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              failed=$((failed+1)) ; echo "::endgroup::" ; echo "::error::build $bsp failed" ; \
+              echo "- ❌ build $bsp failed in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; } && \
+            { total_time=$(grep "Total command execution time" output.log | awk '{print $5}'); \
+              echo "- ✅ build $bsp success in $total_time seconds " >> $GITHUB_STEP_SUMMARY ; echo "::endgroup::" ; }
           done
+          exit $failed
